use_frameworks!

platform :ios, '11.0'

target 'SHPagesView_Example' do
  pod 'SHPagesView', :path => '../'
#  pod 'XDPagesView', :path => '../../XDPagesView'
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']
  pod "SnapKit"
  pod "MJRefresh"
  target 'SHPagesView_Tests' do
    inherit! :search_paths

    
  end
end
